### ISSUE TITLE
Clarification on SigV4 test encoding

### ISSUE THREAD

**Issue by dnys1** [awslabs/aws-c-auth#162]
The SigV4 test suite expects request paths to be URI-encoded one time for the canonical request. For example, [`get-space-normalized`](https://github.com/awslabs/aws-c-auth/tree/main/tests/aws-signing-test-suite/v4/get-space-normalized) expects `/example space/` to be canonicalized as `/example%20space/`. According to the public SigV4 [docs](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html), though, AWS services except S3 expect double-encoded paths in the canonical request (e.g. `/example%2520space/`). This is confirmed through tests against AWS services.

It would help to know if this is expected and we should add a flag in our tests to use single-encoding like S3.

**Comment by graebm** [comment]
By default, a SigV4 signer should URI-encode the path that gets passed in. It assumes that path was already URI-encoded, so we call that "double-encoded".

For S3, the signer does NOT do a second encoding. It uses the path as-is, assuming it's already been encoded once.

For whatever reason, this test exists that has an unencoded " ". The SigV4 signer should encode " " -> "%20", because that's the default behavior. I'm guessing they put a space here just because it's the most common encoding people know.
